name: Clang Format Check

on:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.h'
      - '**/*.cc'
      - '**/*.c'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Install clang-format-18
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-18
          sudo ln -s /usr/bin/clang-format-18 /usr/bin/clang-format

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          files=$(git ls-files '*.cpp' '*.hpp' '*.h' '*.cc' '*.c')
          if [ -n "$files" ]; then
            clang-format --dry-run --Werror $files
          fi